export interface CountryData {
    name: string;
    iso_a3: string;
    ibfSupported: boolean;
    initialZoom: number;
    latlong: [number, number];
}

export const CountryData: Map<string, CountryData> = new Map([
    ["AF", { name: "Afghanistan", iso_a3: "AFG", ibfSupported: false, initialZoom: 5, latlong: [33.94, 67.71] }],
    ["AL", { name: "Albania", iso_a3: "ALB", ibfSupported: false, initialZoom: 5, latlong: [41.15, 20.17] }],
    ["DZ", { name: "Algeria", iso_a3: "DZA", ibfSupported: false, initialZoom: 5, latlong: [28.03, 1.66] }],
    ["AD", { name: "Andorra", iso_a3: "AND", ibfSupported: false, initialZoom: 5, latlong: [42.55, 1.60] }],
    ["AO", { name: "Angola", iso_a3: "AGO", ibfSupported: false, initialZoom: 5, latlong: [-11.20, 17.87] }],
    ["AG", { name: "Antigua and Barbuda", iso_a3: "ATG", ibfSupported: false, initialZoom: 5, latlong: [17.06, -61.80] }],
    ["AR", { name: "Argentina", iso_a3: "ARG", ibfSupported: false, initialZoom: 5, latlong: [-38.42, -63.62] }],
    ["AM", { name: "Armenia", iso_a3: "ARM", ibfSupported: false, initialZoom: 5, latlong: [40.07, 45.04] }],
    ["AU", { name: "Australia", iso_a3: "AUS", ibfSupported: false, initialZoom: 5, latlong: [-25.27, 133.78] }],
    ["AT", { name: "Austria", iso_a3: "AUT", ibfSupported: false, initialZoom: 5, latlong: [47.52, 14.55] }],
    ["AZ", { name: "Azerbaijan", iso_a3: "AZE", ibfSupported: false, initialZoom: 5, latlong: [40.14, 47.58] }],
    ["BS", { name: "Bahamas", iso_a3: "BHS", ibfSupported: false, initialZoom: 5, latlong: [25.03, -77.40] }],
    ["BH", { name: "Bahrain", iso_a3: "BHR", ibfSupported: false, initialZoom: 5, latlong: [26.07, 50.56] }],
    ["BD", { name: "Bangladesh", iso_a3: "BGD", ibfSupported: false, initialZoom: 5, latlong: [23.68, 90.36] }],
    ["BB", { name: "Barbados", iso_a3: "BRB", ibfSupported: false, initialZoom: 5, latlong: [13.19, -59.54] }],
    ["BY", { name: "Belarus", iso_a3: "BLR", ibfSupported: false, initialZoom: 5, latlong: [53.71, 27.95] }],
    ["BE", { name: "Belgium", iso_a3: "BEL", ibfSupported: false, initialZoom: 5, latlong: [50.50, 4.47] }],
    ["BZ", { name: "Belize", iso_a3: "BLZ", ibfSupported: false, initialZoom: 5, latlong: [17.19, -88.50] }],
    ["BJ", { name: "Benin", iso_a3: "BEN", ibfSupported: false, initialZoom: 5, latlong: [9.31, 2.32] }],
    ["BT", { name: "Bhutan", iso_a3: "BTN", ibfSupported: false, initialZoom: 5, latlong: [27.51, 90.43] }],
    ["BO", { name: "Bolivia", iso_a3: "BOL", ibfSupported: false, initialZoom: 5, latlong: [-16.29, -63.59] }],
    ["BA", { name: "Bosnia and Herzegovina", iso_a3: "BIH", ibfSupported: false, initialZoom: 5, latlong: [43.92, 17.68] }],
    ["BW", { name: "Botswana", iso_a3: "BWA", ibfSupported: false, initialZoom: 5, latlong: [-22.33, 24.68] }],
    ["BR", { name: "Brazil", iso_a3: "BRA", ibfSupported: false, initialZoom: 5, latlong: [-14.24, -51.93] }],
    ["BN", { name: "Brunei", iso_a3: "BRN", ibfSupported: false, initialZoom: 5, latlong: [4.54, 114.73] }],
    ["BG", { name: "Bulgaria", iso_a3: "BGR", ibfSupported: false, initialZoom: 5, latlong: [42.73, 25.49] }],
    ["BF", { name: "Burkina Faso", iso_a3: "BFA", ibfSupported: false, initialZoom: 5, latlong: [12.24, -1.56] }],
    ["BI", { name: "Burundi", iso_a3: "BDI", ibfSupported: false, initialZoom: 5, latlong: [-3.37, 29.92] }],
    ["CV", { name: "Cabo Verde", iso_a3: "CPV", ibfSupported: false, initialZoom: 5, latlong: [16.00, -24.01] }],
    ["KH", { name: "Cambodia", iso_a3: "KHM", ibfSupported: false, initialZoom: 5, latlong: [12.57, 104.99] }],
    ["CM", { name: "Cameroon", iso_a3: "CMR", ibfSupported: false, initialZoom: 5, latlong: [7.37, 12.35] }],
    ["CA", { name: "Canada", iso_a3: "CAN", ibfSupported: false, initialZoom: 5, latlong: [56.13, -106.35] }],
    ["CF", { name: "Central African Republic", iso_a3: "CAF", ibfSupported: false, initialZoom: 5, latlong: [6.61, 20.94] }],
    ["TD", { name: "Chad", iso_a3: "TCD", ibfSupported: false, initialZoom: 5, latlong: [15.45, 18.73] }],
    ["CL", { name: "Chile", iso_a3: "CHL", ibfSupported: false, initialZoom: 5, latlong: [-35.68, -71.54] }],
    ["CN", { name: "China", iso_a3: "CHN", ibfSupported: false, initialZoom: 5, latlong: [35.86, 104.20] }],
    ["CO", { name: "Colombia", iso_a3: "COL", ibfSupported: true, initialZoom: 5, latlong: [4.57, -74.30] }],
    ["KM", { name: "Comoros", iso_a3: "COM", ibfSupported: false, initialZoom: 5, latlong: [-11.88, 43.87] }],
    ["CG", { name: "Congo", iso_a3: "COG", ibfSupported: false, initialZoom: 5, latlong: [-0.23, 15.83] }],
    ["CD", { name: "Congo (Democratic Republic)", iso_a3: "COD", ibfSupported: false, initialZoom: 5, latlong: [-4.04, 21.76] }],
    ["CR", { name: "Costa Rica", iso_a3: "CRI", ibfSupported: false, initialZoom: 5, latlong: [9.75, -83.75] }],
    ["CI", { name: "Côte d'Ivoire", iso_a3: "CIV", ibfSupported: false, initialZoom: 5, latlong: [7.54, -5.55] }],
    ["HR", { name: "Croatia", iso_a3: "HRV", ibfSupported: false, initialZoom: 5, latlong: [45.10, 15.20] }],
    ["CU", { name: "Cuba", iso_a3: "CUB", ibfSupported: false, initialZoom: 5, latlong: [21.52, -77.78] }],
    ["CY", { name: "Cyprus", iso_a3: "CYP", ibfSupported: false, initialZoom: 5, latlong: [35.13, 33.43] }],
    ["CZ", { name: "Czechia", iso_a3: "CZE", ibfSupported: false, initialZoom: 5, latlong: [49.82, 15.47] }],
    ["DK", { name: "Denmark", iso_a3: "DNK", ibfSupported: false, initialZoom: 5, latlong: [56.26, 9.50] }],
    ["DJ", { name: "Djibouti", iso_a3: "DJI", ibfSupported: false, initialZoom: 5, latlong: [11.83, 42.59] }],
    ["DM", { name: "Dominica", iso_a3: "DMA", ibfSupported: false, initialZoom: 5, latlong: [15.41, -61.37] }],
    ["DO", { name: "Dominican Republic", iso_a3: "DOM", ibfSupported: false, initialZoom: 5, latlong: [18.74, -70.16] }],
    ["EC", { name: "Ecuador", iso_a3: "ECU", ibfSupported: false, initialZoom: 5, latlong: [-1.83, -78.18] }],
    ["EG", { name: "Egypt", iso_a3: "EGY", ibfSupported: false, initialZoom: 5, latlong: [26.82, 30.80] }],
    ["SV", { name: "El Salvador", iso_a3: "SLV", ibfSupported: false, initialZoom: 5, latlong: [13.79, -88.90] }],
    ["GQ", { name: "Equatorial Guinea", iso_a3: "GNQ", ibfSupported: false, initialZoom: 5, latlong: [1.65, 10.27] }],
    ["ER", { name: "Eritrea", iso_a3: "ERI", ibfSupported: false, initialZoom: 5, latlong: [15.18, 39.78] }],
    ["EE", { name: "Estonia", iso_a3: "EST", ibfSupported: false, initialZoom: 5, latlong: [58.60, 25.01] }],
    ["SZ", { name: "Eswatini", iso_a3: "SWZ", ibfSupported: false, initialZoom: 5, latlong: [-26.52, 31.47] }],
    ["ET", { name: "Ethiopia", iso_a3: "ETH", ibfSupported: true, initialZoom: 5, latlong: [9.15, 40.49] }],
    ["FJ", { name: "Fiji", iso_a3: "FJI", ibfSupported: false, initialZoom: 5, latlong: [-17.71, 178.07] }],
    ["FI", { name: "Finland", iso_a3: "FIN", ibfSupported: false, initialZoom: 5, latlong: [61.92, 25.75] }],
    ["FR", { name: "France", iso_a3: "FRA", ibfSupported: false, initialZoom: 5, latlong: [46.23, 2.21] }],
    ["GA", { name: "Gabon", iso_a3: "GAB", ibfSupported: false, initialZoom: 5, latlong: [-0.80, 11.61] }],
    ["GM", { name: "Gambia", iso_a3: "GMB", ibfSupported: false, initialZoom: 5, latlong: [13.44, -15.31] }],
    ["GE", { name: "Georgia", iso_a3: "GEO", ibfSupported: false, initialZoom: 5, latlong: [42.32, 43.36] }],
    ["DE", { name: "Germany", iso_a3: "DEU", ibfSupported: false, initialZoom: 5, latlong: [51.17, 10.45] }],
    ["GH", { name: "Ghana", iso_a3: "GHA", ibfSupported: false, initialZoom: 5, latlong: [7.95, -1.02] }],
    ["GR", { name: "Greece", iso_a3: "GRC", ibfSupported: false, initialZoom: 5, latlong: [39.07, 21.82] }],
    ["GD", { name: "Grenada", iso_a3: "GRD", ibfSupported: false, initialZoom: 5, latlong: [12.12, -61.68] }],
    ["GT", { name: "Guatemala", iso_a3: "GTM", ibfSupported: false, initialZoom: 5, latlong: [15.78, -90.23] }],
    ["GN", { name: "Guinea", iso_a3: "GIN", ibfSupported: false, initialZoom: 5, latlong: [9.95, -9.70] }],
    ["GW", { name: "Guinea-Bissau", iso_a3: "GNB", ibfSupported: false, initialZoom: 5, latlong: [11.80, -15.18] }],
    ["GY", { name: "Guyana", iso_a3: "GUY", ibfSupported: false, initialZoom: 5, latlong: [4.86, -58.93] }],
    ["HT", { name: "Haiti", iso_a3: "HTI", ibfSupported: false, initialZoom: 5, latlong: [18.97, -72.29] }],
    ["HN", { name: "Honduras", iso_a3: "HND", ibfSupported: false, initialZoom: 5, latlong: [15.20, -86.24] }],
    ["HU", { name: "Hungary", iso_a3: "HUN", ibfSupported: false, initialZoom: 5, latlong: [47.16, 19.50] }],
    ["IS", { name: "Iceland", iso_a3: "ISL", ibfSupported: false, initialZoom: 5, latlong: [64.96, -19.02] }],
    ["IN", { name: "India", iso_a3: "IND", ibfSupported: false, initialZoom: 5, latlong: [20.59, 78.96] }],
    ["ID", { name: "Indonesia", iso_a3: "IDN", ibfSupported: false, initialZoom: 5, latlong: [-0.79, 113.92] }],
    ["IR", { name: "Iran", iso_a3: "IRN", ibfSupported: false, initialZoom: 5, latlong: [32.43, 53.69] }],
    ["IQ", { name: "Iraq", iso_a3: "IRQ", ibfSupported: false, initialZoom: 5, latlong: [33.22, 43.68] }],
    ["IE", { name: "Ireland", iso_a3: "IRL", ibfSupported: false, initialZoom: 5, latlong: [53.14, -7.69] }],
    ["IL", { name: "Israel", iso_a3: "ISR", ibfSupported: false, initialZoom: 5, latlong: [31.05, 34.85] }],
    ["IT", { name: "Italy", iso_a3: "ITA", ibfSupported: false, initialZoom: 5, latlong: [41.87, 12.57] }],
    ["JM", { name: "Jamaica", iso_a3: "JAM", ibfSupported: false, initialZoom: 5, latlong: [18.11, -77.30] }],
    ["JP", { name: "Japan", iso_a3: "JPN", ibfSupported: false, initialZoom: 5, latlong: [36.20, 138.25] }],
    ["JO", { name: "Jordan", iso_a3: "JOR", ibfSupported: false, initialZoom: 5, latlong: [30.59, 36.24] }],
    ["KZ", { name: "Kazakhstan", iso_a3: "KAZ", ibfSupported: false, initialZoom: 5, latlong: [48.02, 66.92] }],
    ["KE", { name: "Kenya", iso_a3: "KEN", ibfSupported: true, initialZoom: 5, latlong: [-0.02, 37.91] }],
    ["KI", { name: "Kiribati", iso_a3: "KIR", ibfSupported: false, initialZoom: 5, latlong: [-3.37, -168.73] }],
    ["KP", { name: "Korea (North)", iso_a3: "PRK", ibfSupported: false, initialZoom: 5, latlong: [40.34, 127.51] }],
    ["KR", { name: "Korea (South)", iso_a3: "KOR", ibfSupported: false, initialZoom: 5, latlong: [35.91, 127.77] }],
    ["KW", { name: "Kuwait", iso_a3: "KWT", ibfSupported: false, initialZoom: 5, latlong: [29.31, 47.48] }],
    ["KG", { name: "Kyrgyzstan", iso_a3: "KGZ", ibfSupported: false, initialZoom: 5, latlong: [41.20, 74.77] }],
    ["LA", { name: "Laos", iso_a3: "LAO", ibfSupported: false, initialZoom: 5, latlong: [19.86, 102.50] }],
    ["LV", { name: "Latvia", iso_a3: "LVA", ibfSupported: false, initialZoom: 5, latlong: [56.88, 24.60] }],
    ["LB", { name: "Lebanon", iso_a3: "LBN", ibfSupported: false, initialZoom: 5, latlong: [33.85, 35.86] }],
    ["LS", { name: "Lesotho", iso_a3: "LSO", ibfSupported: false, initialZoom: 5, latlong: [-29.61, 28.23] }],
    ["LR", { name: "Liberia", iso_a3: "LBR", ibfSupported: false, initialZoom: 5, latlong: [6.43, -9.43] }],
    ["LY", { name: "Libya", iso_a3: "LBY", ibfSupported: false, initialZoom: 5, latlong: [26.34, 17.23] }],
    ["LI", { name: "Liechtenstein", iso_a3: "LIE", ibfSupported: false, initialZoom: 5, latlong: [47.17, 9.56] }],
    ["LT", { name: "Lithuania", iso_a3: "LTU", ibfSupported: false, initialZoom: 5, latlong: [55.17, 23.88] }],
    ["LU", { name: "Luxembourg", iso_a3: "LUX", ibfSupported: false, initialZoom: 5, latlong: [49.82, 6.13] }],
    ["MG", { name: "Madagascar", iso_a3: "MDG", ibfSupported: false, initialZoom: 5, latlong: [-18.77, 46.87] }],
    ["MW", { name: "Malawi", iso_a3: "MWI", ibfSupported: true, initialZoom: 5, latlong: [-13.25, 34.30] }],
    ["MY", { name: "Malaysia", iso_a3: "MYS", ibfSupported: false, initialZoom: 5, latlong: [4.21, 101.98] }],
    ["MV", { name: "Maldives", iso_a3: "MDV", ibfSupported: false, initialZoom: 5, latlong: [3.20, 73.22] }],
    ["ML", { name: "Mali", iso_a3: "MLI", ibfSupported: false, initialZoom: 5, latlong: [17.57, -4.00] }],
    ["MT", { name: "Malta", iso_a3: "MLT", ibfSupported: false, initialZoom: 5, latlong: [35.94, 14.38] }],
    ["MH", { name: "Marshall Islands", iso_a3: "MHL", ibfSupported: false, initialZoom: 5, latlong: [7.13, 171.18] }],
    ["MR", { name: "Mauritania", iso_a3: "MRT", ibfSupported: false, initialZoom: 5, latlong: [21.01, -10.94] }],
    ["MU", { name: "Mauritius", iso_a3: "MUS", ibfSupported: false, initialZoom: 5, latlong: [-20.35, 57.55] }],
    ["MX", { name: "Mexico", iso_a3: "MEX", ibfSupported: false, initialZoom: 5, latlong: [23.63, -102.55] }],
    ["FM", { name: "Micronesia", iso_a3: "FSM", ibfSupported: false, initialZoom: 5, latlong: [7.43, 150.55] }],
    ["MD", { name: "Moldova", iso_a3: "MDA", ibfSupported: false, initialZoom: 5, latlong: [47.41, 28.37] }],
    ["MC", { name: "Monaco", iso_a3: "MCO", ibfSupported: false, initialZoom: 5, latlong: [43.75, 7.41] }],
    ["MN", { name: "Mongolia", iso_a3: "MNG", ibfSupported: false, initialZoom: 5, latlong: [46.86, 103.85] }],
    ["ME", { name: "Montenegro", iso_a3: "MNE", ibfSupported: false, initialZoom: 5, latlong: [42.71, 19.37] }],
    ["MA", { name: "Morocco", iso_a3: "MAR", ibfSupported: false, initialZoom: 5, latlong: [31.79, -7.09] }],
    ["MZ", { name: "Mozambique", iso_a3: "MOZ", ibfSupported: false, initialZoom: 5, latlong: [-18.67, 35.53] }],
    ["MM", { name: "Myanmar", iso_a3: "MMR", ibfSupported: false, initialZoom: 5, latlong: [21.91, 95.96] }],
    ["NA", { name: "Namibia", iso_a3: "NAM", ibfSupported: false, initialZoom: 5, latlong: [-22.96, 18.49] }],
    ["NR", { name: "Nauru", iso_a3: "NRU", ibfSupported: false, initialZoom: 5, latlong: [-0.52, 166.93] }],
    ["NP", { name: "Nepal", iso_a3: "NPL", ibfSupported: false, initialZoom: 5, latlong: [28.39, 84.12] }],
    ["NL", { name: "Netherlands", iso_a3: "NLD", ibfSupported: false, initialZoom: 5, latlong: [52.13, 5.29] }],
    ["NZ", { name: "New Zealand", iso_a3: "NZL", ibfSupported: false, initialZoom: 5, latlong: [-40.90, 174.89] }],
    ["NI", { name: "Nicaragua", iso_a3: "NIC", ibfSupported: false, initialZoom: 5, latlong: [12.87, -85.21] }],
    ["NE", { name: "Niger", iso_a3: "NER", ibfSupported: false, initialZoom: 5, latlong: [17.61, 8.08] }],
    ["NG", { name: "Nigeria", iso_a3: "NGA", ibfSupported: false, initialZoom: 5, latlong: [9.08, 8.68] }],
    ["MK", { name: "North Macedonia", iso_a3: "MKD", ibfSupported: false, initialZoom: 5, latlong: [41.51, 21.75] }],
    ["NO", { name: "Norway", iso_a3: "NOR", ibfSupported: false, initialZoom: 5, latlong: [60.47, 8.47] }],
    ["OM", { name: "Oman", iso_a3: "OMN", ibfSupported: false, initialZoom: 5, latlong: [21.51, 55.92] }],
    ["PK", { name: "Pakistan", iso_a3: "PAK", ibfSupported: false, initialZoom: 5, latlong: [30.38, 69.35] }],
    ["PW", { name: "Palau", iso_a3: "PLW", ibfSupported: false, initialZoom: 5, latlong: [7.51, 134.58] }],
    ["PA", { name: "Panama", iso_a3: "PAN", ibfSupported: false, initialZoom: 5, latlong: [8.54, -80.78] }],
    ["PG", { name: "Papua New Guinea", iso_a3: "PNG", ibfSupported: false, initialZoom: 5, latlong: [-6.31, 143.96] }],
    ["PY", { name: "Paraguay", iso_a3: "PRY", ibfSupported: false, initialZoom: 5, latlong: [-23.44, -58.44] }],
    ["PE", { name: "Peru", iso_a3: "PER", ibfSupported: false, initialZoom: 5, latlong: [-9.19, -75.02] }],
    ["PH", { name: "Philippines", iso_a3: "PHL", ibfSupported: true, initialZoom: 5, latlong: [12.88, 121.77] }],
    ["PL", { name: "Poland", iso_a3: "POL", ibfSupported: false, initialZoom: 5, latlong: [51.92, 19.15] }],
    ["PT", { name: "Portugal", iso_a3: "PRT", ibfSupported: false, initialZoom: 5, latlong: [39.40, -8.22] }],
    ["QA", { name: "Qatar", iso_a3: "QAT", ibfSupported: false, initialZoom: 5, latlong: [25.35, 51.18] }],
    ["RO", { name: "Romania", iso_a3: "ROU", ibfSupported: false, initialZoom: 5, latlong: [45.94, 24.97] }],
    ["RU", { name: "Russia", iso_a3: "RUS", ibfSupported: false, initialZoom: 5, latlong: [61.52, 105.32] }],
    ["RW", { name: "Rwanda", iso_a3: "RWA", ibfSupported: false, initialZoom: 5, latlong: [-1.94, 29.87] }],
    ["KN", { name: "Saint Kitts and Nevis", iso_a3: "KNA", ibfSupported: false, initialZoom: 5, latlong: [17.36, -62.78] }],
    ["LC", { name: "Saint Lucia", iso_a3: "LCA", ibfSupported: false, initialZoom: 5, latlong: [13.91, -60.98] }],
    ["VC", { name: "Saint Vincent and the Grenadines", iso_a3: "VCT", ibfSupported: false, initialZoom: 5, latlong: [12.98, -61.29] }],
    ["WS", { name: "Samoa", iso_a3: "WSM", ibfSupported: false, initialZoom: 5, latlong: [-13.76, -172.10] }],
    ["SM", { name: "San Marino", iso_a3: "SMR", ibfSupported: false, initialZoom: 5, latlong: [43.94, 12.46] }],
    ["ST", { name: "Sao Tome and Principe", iso_a3: "STP", ibfSupported: false, initialZoom: 5, latlong: [0.19, 6.61] }],
    ["SA", { name: "Saudi Arabia", iso_a3: "SAU", ibfSupported: false, initialZoom: 5, latlong: [23.89, 45.08] }],
    ["SN", { name: "Senegal", iso_a3: "SEN", ibfSupported: false, initialZoom: 5, latlong: [14.50, -14.45] }],
    ["RS", { name: "Serbia", iso_a3: "SRB", ibfSupported: false, initialZoom: 5, latlong: [44.02, 21.01] }],
    ["SC", { name: "Seychelles", iso_a3: "SYC", ibfSupported: false, initialZoom: 5, latlong: [-4.68, 55.49] }],
    ["SL", { name: "Sierra Leone", iso_a3: "SLE", ibfSupported: false, initialZoom: 5, latlong: [8.46, -11.78] }],
    ["SG", { name: "Singapore", iso_a3: "SGP", ibfSupported: false, initialZoom: 5, latlong: [1.35, 103.82] }],
    ["SK", { name: "Slovakia", iso_a3: "SVK", ibfSupported: false, initialZoom: 5, latlong: [48.67, 19.70] }],
    ["SI", { name: "Slovenia", iso_a3: "SVN", ibfSupported: false, initialZoom: 5, latlong: [46.15, 14.99] }],
    ["SB", { name: "Solomon Islands", iso_a3: "SLB", ibfSupported: false, initialZoom: 5, latlong: [-9.65, 160.16] }],
    ["SO", { name: "Somalia", iso_a3: "SOM", ibfSupported: false, initialZoom: 5, latlong: [5.15, 46.20] }],
    ["ZA", { name: "South Africa", iso_a3: "ZAF", ibfSupported: false, initialZoom: 5, latlong: [-30.56, 22.94] }],
    ["SS", { name: "South Sudan", iso_a3: "SSD", ibfSupported: false, initialZoom: 5, latlong: [6.88, 31.31] }],
    ["ES", { name: "Spain", iso_a3: "ESP", ibfSupported: false, initialZoom: 5, latlong: [40.46, -3.75] }],
    ["LK", { name: "Sri Lanka", iso_a3: "LKA", ibfSupported: false, initialZoom: 5, latlong: [7.87, 80.77] }],
    ["SD", { name: "Sudan", iso_a3: "SDN", ibfSupported: false, initialZoom: 5, latlong: [12.86, 30.22] }],
    ["SR", { name: "Suriname", iso_a3: "SUR", ibfSupported: false, initialZoom: 5, latlong: [3.92, -56.03] }],
    ["SE", { name: "Sweden", iso_a3: "SWE", ibfSupported: false, initialZoom: 5, latlong: [60.13, 18.64] }],
    ["CH", { name: "Switzerland", iso_a3: "CHE", ibfSupported: false, initialZoom: 5, latlong: [46.82, 8.23] }],
    ["SY", { name: "Syria", iso_a3: "SYR", ibfSupported: false, initialZoom: 5, latlong: [34.80, 39.00] }],
    ["TW", { name: "Taiwan", iso_a3: "TWN", ibfSupported: false, initialZoom: 5, latlong: [23.70, 120.96] }],
    ["TJ", { name: "Tajikistan", iso_a3: "TJK", ibfSupported: false, initialZoom: 5, latlong: [38.86, 71.28] }],
    ["TZ", { name: "Tanzania", iso_a3: "TZA", ibfSupported: true, initialZoom: 5, latlong: [-6.37, 34.89] }],
    ["TH", { name: "Thailand", iso_a3: "THA", ibfSupported: false, initialZoom: 5, latlong: [15.87, 100.99] }],
    ["TL", { name: "Timor-Leste", iso_a3: "TLS", ibfSupported: false, initialZoom: 5, latlong: [-8.87, 125.73] }],
    ["TG", { name: "Togo", iso_a3: "TGO", ibfSupported: false, initialZoom: 5, latlong: [8.62, 0.82] }],
    ["TO", { name: "Tonga", iso_a3: "TON", ibfSupported: false, initialZoom: 5, latlong: [-21.18, -175.20] }],
    ["TT", { name: "Trinidad and Tobago", iso_a3: "TTO", ibfSupported: false, initialZoom: 5, latlong: [10.69, -61.22] }],
    ["TN", { name: "Tunisia", iso_a3: "TUN", ibfSupported: false, initialZoom: 5, latlong: [33.89, 9.54] }],
    ["TR", { name: "Turkey", iso_a3: "TUR", ibfSupported: false, initialZoom: 5, latlong: [38.96, 35.24] }],
    ["TM", { name: "Turkmenistan", iso_a3: "TKM", ibfSupported: false, initialZoom: 5, latlong: [38.97, 59.56] }],
    ["TV", { name: "Tuvalu", iso_a3: "TUV", ibfSupported: false, initialZoom: 5, latlong: [-7.11, 177.65] }],
    ["UG", { name: "Uganda", iso_a3: "UGA", ibfSupported: true, initialZoom: 5, latlong: [1.37, 32.29] }],
    ["UA", { name: "Ukraine", iso_a3: "UKR", ibfSupported: false, initialZoom: 5, latlong: [48.38, 31.17] }],
    ["AE", { name: "United Arab Emirates", iso_a3: "ARE", ibfSupported: false, initialZoom: 5, latlong: [23.42, 53.85] }],
    ["GB", { name: "United Kingdom", iso_a3: "GBR", ibfSupported: false, initialZoom: 5, latlong: [55.38, -3.44] }],
    ["US", { name: "United States", iso_a3: "USA", ibfSupported: false, initialZoom: 5, latlong: [37.09, -95.71] }],
    ["UY", { name: "Uruguay", iso_a3: "URY", ibfSupported: false, initialZoom: 5, latlong: [-32.52, -55.77] }],
    ["UZ", { name: "Uzbekistan", iso_a3: "UZB", ibfSupported: false, initialZoom: 5, latlong: [41.38, 64.59] }],
    ["VU", { name: "Vanuatu", iso_a3: "VUT", ibfSupported: false, initialZoom: 5, latlong: [-15.38, 166.96] }],
    ["VA", { name: "Vatican City", iso_a3: "VAT", ibfSupported: false, initialZoom: 5, latlong: [41.90, 12.45] }],
    ["VE", { name: "Venezuela", iso_a3: "VEN", ibfSupported: false, initialZoom: 5, latlong: [6.42, -66.59] }],
    ["VN", { name: "Vietnam", iso_a3: "VNM", ibfSupported: false, initialZoom: 5, latlong: [14.06, 108.28] }],
    ["YE", { name: "Yemen", iso_a3: "YEM", ibfSupported: false, initialZoom: 5, latlong: [15.55, 48.52] }],
    ["ZM", { name: "Zambia", iso_a3: "ZMB", ibfSupported: false, initialZoom: 5, latlong: [-13.13, 27.85] }],
    ["ZW", { name: "Zimbabwe", iso_a3: "ZWE", ibfSupported: false, initialZoom: 5, latlong: [-19.02, 29.15] }],
]);